name: specvqgan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - appnope=0.1.2
  - astor=0.8.1
  - asttokens=2.0.5
  - attrs=23.1.0
  - audioread=3.0.1
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.12.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.11.0
  - azure-storage-common-cpp=12.6.0
  - azure-storage-files-datalake-cpp=12.10.0
  - backcall=0.2.0
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - base58=2.1.1
  - blas=1.0
  - blinker=1.8.2
  - boto3=1.34.144
  - botocore=1.34.144
  - brotli=1.0.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.7.4
  - cachetools=5.4.0
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.0.4
  - comm=0.2.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.6.2
  - ffmpeg=7.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - graphite2=1.3.14
  - harfbuzz=9.0.0
  - icu=75.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=18.1.8
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libflac=1.4.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.80.3
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.3
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopenvino=2024.2.0
  - libopenvino-arm-cpu-plugin=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-onnx-frontend=2024.2.0
  - libopenvino-paddle-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librosa=0.10.2.post1
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - llvmlite=0.41.0
  - lz4-c=1.9.4
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.32.6
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.1
  - numba=0.58.1
  - numpy-base=1.24.3
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.0.3
  - parso=0.8.3
  - pcre2=10.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.2
  - pyarrow-core=16.1.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.8.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytorch=2.3.1
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.30.2
  - rpds-py=0.10.6
  - s3transfer=0.10.2
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.2.1
  - soxr=0.1.3
  - soxr-python=0.3.7
  - stack_data=0.2.0
  - streamlit=0.80.0
  - svt-av1=2.1.2
  - tbb=2021.12.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - toolz=0.12.0
  - torchvision=0.18.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - tzlocal=5.2
  - unicodedata2=15.1.0
  - urllib3=1.26.19
  - validators=0.33.0
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - albumentations==0.5.2
      - altair==5.3.0
      - async-timeout==4.0.3
      - contourpy==1.1.1
      - filelock==3.15.4
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - future==1.0.0
      - google-auth==2.32.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.65.1
      - imageio==2.34.2
      - imgaug==0.4.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - multidict==6.0.5
      - numpy==1.24.4
      - oauthlib==3.2.2
      - omegaconf==2.0.6
      - opencv-python==4.5.5.64
      - opencv-python-headless==4.5.4.58
      - protobuf==5.27.2
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydeck==0.9.1
      - pytorch-lightning==1.2.10
      - pywavelets==1.4.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - shapely==2.0.5
      - smmap==5.0.1
      - sympy==1.13.0
      - tenacity==8.5.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tifffile==2023.7.10
      - torch==2.3.1
      - torchmetrics==0.2.0
      - tqdm==4.66.4
      - werkzeug==3.0.3
      - yarl==1.9.4